import { useEffect, useState, useCallback } from 'react'
import { supabase } from '../lib/supabase'
import { userColor, memberColor } from '../lib/colors'
import Avatar from './Avatar'

// ── small shared helpers (kept local so the component is self-contained) ──
function fmtScore(s) { return s != null ? Number(s).toFixed(2) : '—' }
function scoreColor(s) {
  if (s == null) return 'var(--text-faint)'
  if (s >= 8.5) return '#fbbf24'
  if (s >= 7) return '#86efac'
  if (s <= 4) return '#f87171'
  return 'var(--accent-light, #fca5a5)'
}
function deltaColor(d) {
  if (d == null) return 'var(--text-faint)'
  if (d <= 1.0) return '#86efac'
  if (d <= 2.0) return '#fbbf24'
  return '#f87171'
}

function Label({ children }) {
  return (
    <p style={{
      fontFamily: "'DM Mono', monospace", fontSize: '9px', letterSpacing: '0.18em',
      textTransform: 'uppercase', color: 'var(--text-dim)', margin: '0 0 10px',
    }}>
      {children}
    </p>
  )
}

// Minimal, safe renderer for the AI recap: splits into paragraphs and renders
// **bold** spans. No raw HTML / dangerouslySetInnerHTML.
export function RecapProse({ text }) {
  const paragraphs = String(text).split(/\n{2,}/).map(p => p.trim()).filter(Boolean)
  const renderInline = (s) => s.split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map((seg, i) => {
    const m = seg.match(/^\*\*([^*]+)\*\*$/)
    return m
      ? <strong key={i} style={{ color: 'var(--text-strong)' }}>{m[1]}</strong>
      : <span key={i}>{seg}</span>
  })
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '9px' }}>
      {paragraphs.map((p, i) => (
        <p key={i} style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '13.5px', color: 'var(--text)', lineHeight: 1.6, margin: 0 }}>
          {renderInline(p)}
        </p>
      ))}
    </div>
  )
}

export default function MonthReveal({ monthId, users = [], currentUserId }) {
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [films, setFilms] = useState([])
  const [ratings, setRatings] = useState([])
  const [guesses, setGuesses] = useState([])
  const [predictions, setPredictions] = useState([])
  const [recap, setRecap] = useState(null)
  const [bestReview, setBestReview] = useState(null)

  const nameById = {}
  const colorById = {}
  const userById = {}
  for (const u of users) { nameById[u.id] = u.name; colorById[u.id] = userColor(u) || memberColor(u.name); userById[u.id] = u }

  const load = useCallback(async () => {
    if (!monthId) return
    setLoading(true)
    setError(null)
    try {
      const { data: movieData, error: mErr } = await supabase
        .from('movies_safe')
        .select('id, title, poster_url, year_released, picked_by_user_id, pick_justification, historical_avg_score, scores_revealed, picker_revealed')
        .eq('month_id', monthId)
      if (mErr) throw mErr
      const movies = movieData ?? []
      const ids = movies.map(m => m.id)

      let ratingsData = [], guessData = [], predData = []
      if (ids.length) {
        const [r, g, p] = await Promise.all([
          supabase.from('ratings').select('movie_id, user_id, score').in('movie_id', ids),
          supabase.from('picker_guesses').select('movie_id, guessing_user_id, guessed_user_id').in('movie_id', ids),
          supabase.from('score_predictions').select('movie_id, predicting_user_id, target_user_id, predicted_score').in('movie_id', ids),
        ])
        ratingsData = r.data ?? []
        guessData = g.data ?? []
        predData = p.data ?? []
      }
      setFilms(movies)
      setRatings(ratingsData)
      setGuesses(guessData)
      setPredictions(predData)

      // AI recap + Best Review (generated by the ai-recap Edge Function; may be absent).
      const { data: recapRow } = await supabase
        .from('month_recaps')
        .select('recap_md, best_review_id, best_review_blurb, generated_at')
        .eq('month_id', monthId)
        .maybeSingle()
      setRecap(recapRow ?? null)
      if (recapRow?.best_review_id) {
        const { data: rev } = await supabase
          .from('reviews')
          .select('id, body, user_id, movie_id')
          .eq('id', recapRow.best_review_id)
          .maybeSingle()
        setBestReview(rev ?? null)
      } else {
        setBestReview(null)
      }
    } catch (e) {
      setError(e.message ?? 'Failed to load reveal.')
    } finally {
      setLoading(false)
    }
  }, [monthId])

  useEffect(() => { load() }, [load])

  if (loading) {
    return <p style={{ fontFamily: "'DM Mono', monospace", fontSize: '12px', color: 'var(--text-dim)' }}>Loading reveal…</p>
  }
  if (error) {
    return <p style={{ fontFamily: "'DM Mono', monospace", fontSize: '12px', color: '#f87171' }}>{error}</p>
  }
  if (!films.length) {
    return <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', color: 'var(--text-dim)' }}>Nothing to reveal yet.</p>
  }

  const bestReviewFilm = bestReview ? films.find(f => f.id === bestReview.movie_id) : null

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {/* AI recap of the month + the AI-picked Best Review */}
      {recap?.recap_md && (
        <div style={{
          background: 'rgba(var(--accent-rgb),0.06)', border: '1px solid rgba(var(--accent-rgb),0.25)',
          borderRadius: '14px', padding: '16px',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '7px', marginBottom: '10px' }}>
            <span aria-hidden="true">✨</span>
            <Label>The Month, Recapped</Label>
          </div>
          <RecapProse text={recap.recap_md} />

          {bestReview && (
            <div style={{ marginTop: '14px', paddingTop: '14px', borderTop: '1px solid rgba(var(--fg-rgb),0.1)' }}>
              <p style={{ fontFamily: "'DM Mono',monospace", fontSize: '10px', textTransform: 'uppercase', letterSpacing: '0.12em', color: '#fbbf24', margin: '0 0 8px' }}>
                🏅 Best Review of the Month
              </p>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px', flexWrap: 'wrap' }}>
                {userById[bestReview.user_id] && <Avatar user={userById[bestReview.user_id]} size={22} ring />}
                <span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '13px', color: 'var(--text-strong)', fontWeight: 600 }}>
                  {nameById[bestReview.user_id] ?? 'A member'}
                </span>
                {bestReviewFilm && (
                  <span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '12px', color: 'var(--text-dim)' }}>
                    on {bestReviewFilm.title}
                  </span>
                )}
              </div>
              <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '13px', color: 'var(--text)', lineHeight: 1.5, margin: '0 0 6px', fontStyle: 'italic' }}>
                “{bestReview.body}”
              </p>
              {recap.best_review_blurb && (
                <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '12px', color: 'var(--text-dim)', lineHeight: 1.45, margin: 0 }}>
                  — {recap.best_review_blurb}
                </p>
              )}
            </div>
          )}
        </div>
      )}

      {films.map(f => {
        const pickerName = f.picked_by_user_id ? (nameById[f.picked_by_user_id] ?? 'Unknown') : 'Unknown'
        const ratingByUser = {}
        for (const r of ratings) if (r.movie_id === f.id && r.score != null) ratingByUser[r.user_id] = r.score
        // Club average for the score badge: prefer the authoritative historical avg,
        // else the mean of the individual revealed scores.
        const scoreVals = Object.values(ratingByUser).map(Number)
        const clubAvg = f.historical_avg_score != null
          ? Number(f.historical_avg_score)
          : (scoreVals.length ? scoreVals.reduce((s, v) => s + v, 0) / scoreVals.length : null)
        // Per-member scores, in the club's user order (test account already excluded).
        const memberScores = users
          .map(u => ({ name: u.name, color: colorById[u.id], score: ratingByUser[u.id] }))
          .filter(m => m.score != null)
          .sort((a, b) => b.score - a.score)

        // Guess-the-picker results for this film. Exclude guesses by the test account
        // (and any unknown user) — it's filtered out of `users`/nameById, so it must not
        // appear as a blank "—" guesser or be counted in "X/Y guessed correctly".
        const filmGuesses = guesses.filter(g => g.movie_id === f.id && nameById[g.guessing_user_id])
        const correctGuessers = filmGuesses.filter(g => g.guessed_user_id === f.picked_by_user_id)
        const myGuess = filmGuesses.find(g => g.guessing_user_id === currentUserId)

        // Picker's predictions for this film
        // Likewise drop predictions targeting an unknown/test user (would render "Unknown").
        const filmPreds = predictions.filter(p => p.movie_id === f.id && p.predicting_user_id === f.picked_by_user_id && nameById[p.target_user_id])

        return (
          <div key={f.id} style={{
            // Match the "Now Showing" FilmCard look (same bg/border/radius + a
            // picker-coloured left edge) so the two columns read as one system.
            background: 'rgba(var(--fg-rgb),0.025)', border: '1px solid rgba(var(--fg-rgb),0.07)',
            borderLeft: colorById[f.picked_by_user_id] ? `3px solid ${colorById[f.picked_by_user_id]}` : '1px solid rgba(var(--fg-rgb),0.07)',
            borderRadius: '14px', padding: '12px',
          }}>
            {/* Header row: poster + title/year + club-average score badge */}
            <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
              <div style={{ flexShrink: 0, width: '48px', height: '68px', borderRadius: '7px', overflow: 'hidden', background: 'var(--surface-2)' }}>
                {f.poster_url && (
                  <img src={`https://image.tmdb.org/t/p/w300${f.poster_url}`} alt={f.title}
                    style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
                    onError={e => { e.target.style.display = 'none' }} />
                )}
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <p style={{ fontFamily: "'DM Mono',monospace", color: 'var(--text-faint)', fontSize: '10px', textTransform: 'uppercase', letterSpacing: '0.1em', margin: '0 0 3px' }}>
                  Club average
                </p>
                <p style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 500, fontSize: '14px', color: 'var(--text-strong)', margin: '0 0 2px', lineHeight: 1.3, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {f.title}
                </p>
                <p style={{ fontFamily: "'DM Mono', monospace", color: 'var(--hairline)', fontSize: '11px', margin: 0 }}>
                  {f.year_released ?? ''}
                </p>
              </div>
              {clubAvg != null && (
                <span style={{
                  flexShrink: 0, fontFamily: "'Bebas Neue',sans-serif", fontSize: '1.25rem', letterSpacing: '0.03em',
                  lineHeight: 1, padding: '6px 10px', borderRadius: '8px',
                  background: 'rgba(var(--fg-rgb),0.04)', border: `1px solid ${scoreColor(clubAvg)}`, color: scoreColor(clubAvg),
                }}>
                  {fmtScore(clubAvg)}
                </span>
              )}
            </div>

            {/* Picker + justification */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '7px', margin: '12px 0 0' }}>
              <Avatar user={userById[f.picked_by_user_id] ?? { name: pickerName }} size={22} />
              <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', color: 'var(--text)' }}>
                Picked by <strong style={{ color: 'var(--text-strong)' }}>{pickerName}</strong>
              </span>
            </div>
            {f.pick_justification && (
              <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '12px', fontStyle: 'italic', color: 'var(--text-muted)', margin: '6px 0 0', lineHeight: 1.55 }}>
                "{f.pick_justification}"
              </p>
            )}

            {/* Per-member scores (everything is revealed here) */}
            {memberScores.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginTop: '12px' }}>
                {memberScores.map((m, i) => (
                  <span key={i} style={{
                    display: 'inline-flex', alignItems: 'center', gap: '5px',
                    fontFamily: "'DM Mono', monospace", fontSize: '11px', padding: '3px 8px', borderRadius: '999px',
                    background: 'rgba(var(--fg-rgb),0.04)', border: '1px solid rgba(var(--fg-rgb),0.08)',
                  }}>
                    <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: m.color, flexShrink: 0 }} />
                    <span style={{ color: 'var(--text-muted)' }}>{m.name.split(' ')[0]}</span>
                    <strong style={{ color: scoreColor(m.score) }}>{fmtScore(m.score)}</strong>
                  </span>
                ))}
              </div>
            )}

            {/* spacer before guess/prediction sections */}
            {(filmGuesses.length || filmPreds.length) ? <div style={{ height: '14px' }} /> : null}

            {/* Guess the picker results */}
            {filmGuesses.length > 0 && (
              <div style={{ marginBottom: filmPreds.length ? '14px' : 0, paddingTop: '12px', borderTop: '1px solid rgba(var(--fg-rgb),0.06)' }}>
                <Label>Guess the Picker</Label>
                <p style={{ fontFamily: "'DM Mono', monospace", fontSize: '11px', color: 'var(--text-muted)', margin: '0 0 8px' }}>
                  {correctGuessers.length}/{filmGuesses.length} guessed correctly
                  {myGuess && (
                    <span style={{ color: myGuess.guessed_user_id === f.picked_by_user_id ? '#86efac' : '#f87171', marginLeft: '8px' }}>
                      · you {myGuess.guessed_user_id === f.picked_by_user_id ? 'nailed it' : 'missed'}
                    </span>
                  )}
                </p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                  {filmGuesses.map((g, i) => {
                    const right = g.guessed_user_id === f.picked_by_user_id
                    return (
                      <span key={i} style={{
                        fontFamily: "'DM Mono', monospace", fontSize: '10px', padding: '3px 8px', borderRadius: '999px',
                        background: 'rgba(var(--fg-rgb),0.05)',
                        border: `1px solid ${right ? '#86efac55' : '#f8717155'}`,
                        color: 'var(--text-muted)',
                      }}>
                        {nameById[g.guessing_user_id] ?? '—'} → {nameById[g.guessed_user_id] ?? '—'} {right ? '✓' : '✗'}
                      </span>
                    )
                  })}
                </div>
              </div>
            )}

            {/* Picker's score predictions vs actual */}
            {filmPreds.length > 0 && (
              <div style={{ paddingTop: '12px', borderTop: '1px solid rgba(var(--fg-rgb),0.06)' }}>
                <Label>Picker's Predictions</Label>
                {filmPreds.map((p, i) => {
                  const actual = ratingByUser[p.target_user_id]
                  const delta = (p.predicted_score != null && actual != null) ? Math.abs(Number(p.predicted_score) - Number(actual)) : null
                  return (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 0', borderBottom: '1px solid rgba(var(--fg-rgb),0.04)' }}>
                      <span style={{ flex: 1, minWidth: 0, fontFamily: "'DM Sans', sans-serif", fontSize: '12px', color: 'var(--text)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {nameById[p.target_user_id] ?? 'Unknown'}
                      </span>
                      <span style={{ fontFamily: "'DM Mono', monospace", fontSize: '11px', color: 'var(--text-dim)' }}>{fmtScore(p.predicted_score)}</span>
                      <span style={{ fontFamily: "'DM Mono', monospace", fontSize: '9px', color: 'var(--text-faint)' }}>→</span>
                      <span style={{ fontFamily: "'DM Mono', monospace", fontSize: '12px', fontWeight: 600, color: scoreColor(actual) }}>{fmtScore(actual)}</span>
                      {delta != null && (
                        <span style={{ fontFamily: "'DM Mono', monospace", fontSize: '9px', color: deltaColor(delta), flexShrink: 0 }}>±{delta.toFixed(2)}</span>
                      )}
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
